### ISSUE TITLE
关于数据中的kg_TransE_l2_entity.npy

### ISSUE THREAD

**Issue by applelalala** [JieZheng-ShanghaiTech/NSF4SL#2]
代码中并没有给出是如何生成kg_TransE_l2_entity.npy，请问生成嵌入的代码可以分享一下吗？另外可以问一下，是gene名字和关系名字生成的嵌入还是gene-id生成的嵌入呢？

**Comment by shikew** [comment]
您好，感谢关注。

相关代码已上传至[data/kg_process](https://github.com/JieZheng-ShanghaiTech/NSF4SL/tree/main/data/kg_process)文件夹，使用的是id生成嵌入。

**Comment by applelalala** [comment]
非常感谢您的回复！
