### ISSUE TITLE
数据不匹配错误

### ISSUE THREAD

**Issue by quocanh0810** [JieZheng-ShanghaiTech/NSF4SL#5]
在文件 process_kg.ipynb 中处理时出现数据错误，id 与文件gene_id.npy 不匹配.

我尝试重新训练 process_kg.ipynb 文件中的数据并获得新的 kg_TransE_l2_entity.npy。 但运行时，数据与gene_id.npy文件不匹配

**Comment by shikew** [comment]
您好，感谢关注。

请参考dataload.py中geneid2index_kgemb的[mapping函数](https://github.com/JieZheng-ShanghaiTech/NSF4SL/blob/main/data_loader.py#L22)，它提供了从gene_id到kg_embeddings的映射。此外函数[getFeat(self, gene_id)](https://github.com/JieZheng-ShanghaiTech/NSF4SL/blob/main/data_loader.py#L54)中提供了使用示例。
